--数学公式编辑器
--为优雅的输入数学公式而生
--作者：Duo  QQ：113530014
--更新日志：
--       11.22.am：写键盘框架，项目名：数学公式编辑器
--       11.22.pm：优化f(x)输入，新增计算功能

--我们旨在将math.sin(例)替换为sin从而方便输入计算
--注意：例如要输入√2，请输入√(x)
--常用函数在f(x)中可以找到


--本人用平板电脑编写，手机查看时布局如有异常请指出😘


local uiManager=this.uiManager
local themeConfig=uiManager.themeConfig
local colors="0"--themeConfig.getColors()--主题色跟随
local MaterialCardView = luajava.bindClass "com.google.android.material.card.MaterialCardView"
import "androidx.cardview.widget.CardView"
import "androidx.appcompat.widget.AppCompatSpinner"
import "androidx.appcompat.widget.PopupMenu"
import "android.widget.PopupMenu"
import "java.io.File"--导入File类

h=activity.getHeight()
w=activity.getWidth()




铎={
  FrameLayout,
  {
    CardView;--卡片控件
    layout_margin='8dp';--边距
    --layout_gravity='center';--重力
    --左:left 右:right 中:center 顶:top 底:bottom
    layout_marginTop='20dp';--顶距
    elevation='2dp';--阴影
    layout_width='fill';--宽度
    layout_height=h-1090;--高度
    CardBackgroundColor='#ffffffff';--颜色
    radius='8dp';--圆角
    {
      EditText;
      layout_width="fill";
      id="计算框";
      layout_height="fill";
      background="#00000000";
      gravity="left";
    };
  };

  {
    LinearLayout;
    layout_width="fill";
    layout_marginTop=h-1050;--顶距
    {
      CardView;
      layout_margin="10dp";
      layout_height="43dp";
      layout_width="fill";
      radius='6dp';--卡片圆角
      {
        EditText;
        id="edit";
        layout_marginLeft='10dp';--布局左距
        background="#FFFFFFFF";
        layout_gravity="center";
        gravity="left";
        textSize="16sp",--文本大小
        --  imeOptions="actionSearch";--设置键盘右下角操作
        id="编辑框",
        singleLine="true";
        Hint="Enter math problem";
        layout_width="fill";
      };

      {
        MaterialCardView,
        elevation="0",
        radius="30dp",
        layout_gravity="center|right";
        cardBackgroundColor="#FFFCFCFC",
        layout_marginRight='75dp';--右距
        layout_width="35dp",
        layout_height="35dp",
        cardElevation=0,
        id="清空";
        onClick=function()
          编辑框.setText("");
          task(80,function()--1000毫秒=1秒
            清空.Visibility=8;--隐藏控件
          end)

        end,
        {
          TextView,
          --textColor="#ff000000",
          text="清空",
          textSize="15sp",
          layout_gravity='center';--卡片重力
        };
      };
      {
        MaterialCardView,
        elevation="0",
        --radius="5dp",
        layout_gravity="center|right";
        cardBackgroundColor="#FFE9E9E9",
        layout_width="70dp",
        layout_height="48dp",
        cardElevation=0,
        id="完成",
        {
          TextView,
          --textColor="#ff000000",
          text="OK",
          textSize="15sp",
          layout_gravity='center';--卡片重力
        };
      };
    };
  };

  {
    LinearLayout,--线性布局
    --orientation='vertical',--方向
    layout_width='fill',--宽度
    layout_height='130',--高度
    layout_marginTop=h-850;--顶距
    background='#00FFFFFF',--背景颜色或图片路径
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginLeft='3.75%w';--左距
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("x");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" x ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("y");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" y ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("π");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" π ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("e");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" е ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("7");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 7 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("8");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 8 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("9");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 9 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
  };

  --###########################################

  {
    LinearLayout,--线性布局
    --orientation='vertical',--方向
    layout_width='fill',--宽度
    layout_height='130',--高度
    layout_marginTop=h-700;--顶距
    background='#00FFFFFF',--背景颜色或图片路径
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginLeft='3.75%w';--左距
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("^");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" ^ ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("√");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" √ ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("abs");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" |□| ",
        textSize="15sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      id="选择函数";
      onClick=function()
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" f(x) ",
        textSize="15sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("4");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 4 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("5");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 5 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("6");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 6 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
  };

  --##############################################

  {
    LinearLayout,--线性布局
    --orientation='vertical',--方向
    layout_width='fill',--宽度
    layout_height='130',--高度
    layout_marginTop=(h-550);--顶距
    background='#00FFFFFF',--背景颜色或图片路径
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginLeft='3.75%w';--左距
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("+");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" + ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("-");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" - ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("*");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" * ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("/");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" / ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("1");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 1 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("2");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 2 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("3");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 3 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
  };


  --###########################################

  {
    LinearLayout,--线性布局
    --orientation='vertical',--方向
    layout_width='fill',--宽度
    layout_height='130',--高度
    layout_marginTop=(h-400);--顶距
    background='#00FFFFFF',--背景颜色或图片路径
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginLeft='3.75%w';--左距
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        print("待添加")
      end,
      {
        TextView,
        --textColor="#ff000000",
        text="more",
        textSize="15sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append(",");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" , ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("(");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" ( ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append(")");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" ) ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("0");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" 0 ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append(".");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" . ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
    {
      MaterialCardView,
      elevation="0",
      radius="5dp",
      layout_marginRight="8dp",
      layout_marginBottom="8dp",
      cardBackgroundColor="#FFC2C2C2",
      layout_width="10%w",
      layout_height="125",
      layout_marginRight='3.75%w';--左距
      cardElevation=0,
      cardBackgroundColor=colors.colorAccent,
      onClick=function()
        编辑框.append("=");
        清空.Visibility=0;--显示控件
      end,
      {
        TextView,
        --textColor="#ff000000",
        text=" = ",
        textSize="25sp",
        layout_gravity='center';--卡片重力
      };
    };
  };
};

--this.uiManager.getFragment(0).view.addView(loadlayout(铎))
--activity.setContentView(loadlayout(铎))
webView.addView(loadlayout(铎))

清空.Visibility=8;--隐藏控件
计算框.append([[输入数学问题，点击"Ok"，这里会显示运算结果。]])

选择函数.onClick=function()--点击事件
  pop=PopupMenu(activity,选择函数)
  menu=pop.Menu
  menu.add("sin").onMenuItemClick=function(a)
    编辑框.append("sin");
    清空.Visibility=0;--显示控件
  end
  menu.add("cos").onMenuItemClick=function(a)
    编辑框.append("cos");
    清空.Visibility=0;--显示控件
  end
  menu.add("tan").onMenuItemClick=function(a)
    编辑框.append("tan");
    清空.Visibility=0;--显示控件
  end
  menu.add("log₁₀").onMenuItemClick=function(a)
    编辑框.append("log₁₀");
    清空.Visibility=0;--显示控件
  end
  menu.add("floor").onMenuItemClick=function(a)
    编辑框.append("floor");
    清空.Visibility=0;--显示控件
  end
  menu.add("min").onMenuItemClick=function(a)
    编辑框.append("min");
    清空.Visibility=0;--显示控件
  end
  menu.add("max").onMenuItemClick=function(a)
    编辑框.append("max");
    清空.Visibility=0;--显示控件
  end

  pop.show()
end;




完成.onClick=function()--点击事件
  原始数据=编辑框.Text
  if 原始数据=="" then print("输入不得为空") else
    处理后=string.gsub(原始数据,"π","math.pi")
    处理后=string.gsub(处理后,"e","math.exp(1)")
    处理后=string.gsub(处理后,"√","math.sqrt")
    处理后=string.gsub(处理后,"sin","math.sin")
    处理后=string.gsub(处理后,"cos","math.cos")
    处理后=string.gsub(处理后,"tan","math.tan")
    处理后=string.gsub(处理后,"max","math.max")
    处理后=string.gsub(处理后,"min","math.min")
    处理后=string.gsub(处理后,"floor","math.floor")
    处理后=string.gsub(处理后,"log₁₀","math.log10")
    处理后=string.gsub(处理后,"abs","math.abs")
    --print(处理后)
    if string.find(处理后,"=")==nil then
      assert(loadstring("计算结果=tostring("..处理后..")"))()
      计算框.append("\n计算："..原始数据.."="..计算结果.."")
     else
      计算框.append("\n求根："..原始数据.."这个我暂时还不会")
    end
  编辑框.setText("");
  清空.Visibility=8;--隐藏控件
  end
end


